name: Build & Test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - './github/*'
      - './.gitignore'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - './github/*'
      - './.gitignore'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Restore cache
      uses: actions/cache@v4.2.3
      with:
        path: ./target
        key: rust-target-${{ matrix.os }}
    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
